New updates for API workflow End to End
john-hawkins/DataRobot_Workflows pull request #1
Opened 2019-10-31 22:00 UTC by eujinlok

Hi John and Jesse 

Please accept my pull request for this new branch. This is the same python workflow API but updated with recent updates from DataRobot. I've documented the workflow and steps to reproduce in the Readme file in the new API_Workflow_EndtoEnd folder

Thanks
EJ

2019-11-05 00:39 UTC, jessezwu commented on API_Workflow_EndtoEnd/.ipynb_checkpoints/1. Model Training-checkpoint.ipynb
> +    "Using the API to train a model on DataRobot, and serealise the model  \n",
typo :)

2019-11-05 00:41 UTC, jessezwu commented on API_Workflow_EndtoEnd/4.Model_Monitoring_Management.py
> +USERNAME = 'eu.jin.lok@datarobot.com'
Probably remove this

2019-11-05 00:42 UTC, john-hawkins requested changes
Hey Eu Jin

Please note that this is a public repository.
You have your API Key and DataRobot Key in this commit.
This would allow anyone else to use your DataRobot account.

I usually add a dummy file with 'XXXXXXXXXXXXXXXX'
So that users know what to do.

Also, I strongly recommend adding any custom functions in a separate python file.
Notebooks are great for data scientists, but annoying for people who need to manage
deployed code.

Cheers
John

2019-11-05 00:43 UTC, john-hawkins commented on API_Workflow_EndtoEnd/4.Model_Monitoring_Management.py
> +USERNAME = 'eu.jin.lok@datarobot.com'
Jesse means your email address

2019-11-05 00:44 UTC, john-hawkins commented
Eu Jin,

Note that you will need to remove these commits from your GitHub history.

Otherwise, someone nefarious could check the commit history and find your credentials.

Cheers
John

2019-11-05 05:04 UTC, eujinlok commented
Thanks @john-hawkins  

My bad, I forgot to update the gitignore file to not commit the credentials. I've gone back and erased historical commits now. Let me know if you still see any trails of my creds anywhere 

Just the last one, what custom function are you referring to?

2019-12-02 23:56 UTC, john-hawkins approved these changes
Thanks Eu Jin,

Looks good, I don't see credentials in there anymore :-)

I will show you an example of what I meant by that other comment.

2019-12-02 23:56 UTC, merged